Repository newrelic/newrelic-node-nextjs, pull requests merged in 2024-04, with the labels that each got.

#185 ci: removed changelog.json file
  changelog.json
Labels: dev:automation

#186 ci: Removed `use_new_release` input from prepare release workflow
  .github/workflows/prepare-release.yml
Labels: dev:automation

#187 test: Added targets for compatibility reporting
  tests/versioned/package.json
Labels: dev:tests

#188 chore: Enabled quiet mode for CI runs
  .github/workflows/ci-workflow.yml
  THIRD_PARTY_NOTICES.md
  bin/run-versioned-tests.sh
  package-lock.json
  package.json
  third_party_manifest.json
Labels: dev:tests

#190 docs: Added FAQs to assist with common issues with next.js instrumentation
  README.md
  docs/faqs/README.md
  docs/faqs/browser-agent.md
  docs/faqs/cloud-providers.md
  docs/faqs/error-handling.md
  docs/faqs/instrument-third-party-libraries.md
Labels: documentation

#191 chore: Made pre-commit hook require dependency changes
  .husky/pre-commit
  bin/update-third-party-notices.sh
Labels: dev:automation
